service: voicefoundry-challenge

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  environment:
    accountId: '#{AWS::AccountId}'
    BUCKET_NAME: voice-foundry-bucket
    TABLE_NAME: books
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:BatchWriteItem
      Resource:
        - !GetAtt BookTable.Arn
    - Effect: Allow
      Action:
        - s3:getObject
        - s3:getObjectAcl
      Resource:
        - Fn::Join:
            - ''
            - - !GetAtt VoiceFoundryBucket.Arn
              - '*'
# This grabs the attribute "Arn (Amazon Resource Name) from the HelloTable logical value, much cleaner"

plugins:
  - invoke-on-deploy
  - serverless-s3-sync

custom:
  s3Sync:
    - bucketName: voice-foundry-bucket
      localDir: /data

functions:
  savebooks:
    handler: lambda.savebooks

# you can add CloudFormation resource templates here
resources:
  Resources:
    VoiceFoundryBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: voice-foundry-bucket

    BookTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: books
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
